version: '3.8'

services:

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=claimmanagement
      - MYSQL_USER=anand
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql-data:/var/lib/mysql
      
  bank-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=claimmanagement
      - DB_USERNAME=anand
      - DB_PASSWORD=password
    depends_on:
      - mysql

  # bank-ui:
  #   image: anandageethan/bank-ui:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #      - REACT_APP_BACKEND_URL=http://bank-api:9090
  #   depends_on:
  #   - bank-api
  #   - mysql

volumes:
  mysql-data: