version: '3.8'

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: claimmanagement
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
      
  bank-api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: anandageethan/bank-api:latest
    ports:
      - "9090:9090"
    environment:
      DB_HOST: mysql
      DB_NAME: claimmanagement
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  bank-ui:
    image: anandageethan/bank-ui:latest
    ports:
      - 8080:8080
    environment:
       - REACT_APP_BACKEND_URL=http://bank-api:9090
    depends_on:
    - bank-api
    - mysql

volumes:
  mysql-data: